# Generated by Django 3.0.8 on 2020-08-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='author', to='Reading.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='category', to='Reading.Category'),
        ),
    ]
