# Generated by Django 3.0.8 on 2020-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0002_auto_20200813_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
